name: "unity-sonarscanner"
description: "Run analysis for mono via dotnet-sonarscanner"
author: "Paul Pacheco <paulpach@gmail.com>"

inputs:
  buildCommand:
    description: "Command to invoke build"
    required: true
  testCommand:
    description: "Command to invoke tests"
    required: false
  projectKey:
    description: "Specifies the key of the analyzed project in SonarQube"
    required: true
  projectName:
    description: "Specifies the name of the analyzed project in SonarQube"
    required: true
  sonarHostname:
    description: "The server URL"
    default: "https://sonarcloud.io"
    required: false
  sonarOrganisation:
    description: "Organisation"
    required: true
  beginArguments:
    description: "Arguments to append to the begin command"
    required: false
  endArguments:
    description: "Arguments to append to the end command"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: 'check'
  color: 'purple'
