name: Run tests

on: pull_request

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Create artifact dir
        run: |
          mkdir -p artifacts
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
    
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.6
        with:
          unityVersion: 2020.3.25f1